workspace:
  base: /go
  path: src/github.com/gboddin/sembump

pipeline:
  build:
    image: golang:1.8
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure 
      - mkdir build
      - GOOS=linux GOARCH=amd64 go build -o build/sembump-linux-amd64
      - GOOS=linux GOARCH=arm go build -o build/sembump-linux-arm
      - GOOS=linux GOARCH=386 go build -o build/sembump-linux-386
      - GOOS=darwin GOARCH=amd64 go build -o build/sembump-macos-amd64
      - GOOS=darwin GOARCH=386 go build -o build/sembump-macos-386
      - GOOS=windows GOARCH=amd64 go build -o build/sembump-amd64.exe
      - GOOS=windows GOARCH=386 go build -o build/sembump-386.exe

  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: build/** 
    checksum:
      - sha256
    when:
      event: tag
